// Central Thai audio. Priority:
//   1. Pre-recorded MP3s (public/audio/, generated by scripts/gen-audio.mjs
//      with a neural TTS — near-native quality, same on every device).
//   2. Web Speech API with the BEST available Thai voice — some devices have
//      several and default to the worst; we rank and cache the good one.
// The manifest (public/audio/manifest.json) maps exact Thai strings to MP3
// files; anything not in it falls back to Web Speech, so the app works the
// same before and after audio generation.

import { Platform } from 'react-native';

const BASE_PATH = process.env.EXPO_PUBLIC_BASE_PATH ?? '/sanuk-thai';

let manifest: Record<string, string> | null = null;
let manifestLoading = false;

function loadManifest() {
  if (manifest || manifestLoading || Platform.OS !== 'web') return;
  manifestLoading = true;
  fetch(`${BASE_PATH}/audio/manifest.json`)
    .then(r => (r.ok ? r.json() : {}))
    .then(j => { manifest = j && typeof j === 'object' ? (j as Record<string, string>) : {}; })
    .catch(() => { manifest = {}; });
}

// Known-good Thai voices first (iOS "Kanya"/"Narisa", Google's th-TH voices).
function pickThaiVoice(): SpeechSynthesisVoice | null {
  const voices = window.speechSynthesis.getVoices();
  const thai = voices.filter(v => /^th([-_]|$)/i.test(v.lang));
  if (thai.length === 0) return null;
  const score = (v: SpeechSynthesisVoice) =>
    (/kanya|narisa|premwadee|achara/i.test(v.name) ? 4 : 0) +
    (/google/i.test(v.name) ? 3 : 0) +
    (v.localService ? 0 : 1) +           // network voices usually sound better
    (/enhanced|premium/i.test(v.name) ? 2 : 0);
  return thai.sort((a, b) => score(b) - score(a))[0];
}

let cachedVoice: SpeechSynthesisVoice | null = null;
let voicesHooked = false;

let player: HTMLAudioElement | null = null;

export function speakThai(text: string, rate = 0.8): void {
  if (Platform.OS !== 'web' || typeof window === 'undefined') return;
  loadManifest();

  // 1. Recorded audio
  const file = manifest?.[text];
  if (file) {
    try {
      window.speechSynthesis?.cancel();
      if (!player) player = new Audio();
      player.pause();
      player.playbackRate = 1;
      player.onended = null;
      player.src = `${BASE_PATH}/audio/${file}`;
      player.play().catch(() => fallbackSpeak(text, rate));
      return;
    } catch {
      // fall through to TTS
    }
  }
  fallbackSpeak(text, rate);
}

// Speak and resolve when playback finishes — drives sequenced speech like the
// read-along highlight. Uses the same recorded-first/Web-Speech-fallback
// priority as speakThai. Never rejects, and a stuck backend can't hang the
// caller: a duration-based timeout always resolves.
export function speakThaiAsync(text: string, rate = 0.8): Promise<void> {
  return new Promise(resolve => {
    if (Platform.OS !== 'web' || typeof window === 'undefined') return resolve();
    loadManifest();

    let done = false;
    const finish = () => { if (!done) { done = true; resolve(); } };
    const guard = setTimeout(finish, 10000);
    const settle = () => { clearTimeout(guard); finish(); };

    const file = manifest?.[text];
    if (file) {
      try {
        window.speechSynthesis?.cancel();
        if (!player) player = new Audio();
        player.pause();
        // Recordings are already at learner speed (0.9×): the read-along's
        // default 0.75 plays them natural, other speeds scale around that.
        player.playbackRate = Math.max(0.5, Math.min(1.25, rate / 0.75));
        player.onended = settle;
        player.onerror = settle;
        player.src = `${BASE_PATH}/audio/${file}`;
        player.play().catch(settle);
        return;
      } catch {
        // fall through to TTS
      }
    }

    const synth = window.speechSynthesis;
    if (!synth) return settle();
    if (!cachedVoice) cachedVoice = pickThaiVoice();
    synth.cancel();
    const u = new SpeechSynthesisUtterance(text);
    u.lang = 'th-TH';
    u.rate = rate;
    if (cachedVoice) u.voice = cachedVoice;
    u.onend = settle;
    u.onerror = settle;
    synth.speak(u);
  });
}

// Stop whatever is speaking — recorded clip or Web Speech utterance.
export function stopSpeaking(): void {
  if (Platform.OS !== 'web' || typeof window === 'undefined') return;
  try { player?.pause(); } catch { /* already stopped */ }
  window.speechSynthesis?.cancel();
}

function fallbackSpeak(text: string, rate: number) {
  const synth = window.speechSynthesis;
  if (!synth) return;
  // Voice list loads async on some browsers — refresh the cache when it does.
  if (!voicesHooked) {
    voicesHooked = true;
    synth.addEventListener?.('voiceschanged', () => { cachedVoice = pickThaiVoice(); });
  }
  if (!cachedVoice) cachedVoice = pickThaiVoice();
  synth.cancel();
  const u = new SpeechSynthesisUtterance(text);
  u.lang = 'th-TH';
  u.rate = rate;
  if (cachedVoice) u.voice = cachedVoice;
  synth.speak(u);
}

export function speechAvailable(): boolean {
  return Platform.OS === 'web' && typeof window !== 'undefined' && !!window.speechSynthesis;
}
