// Stamps the build with a unique id so running apps can detect new deploys.
// Writes:
//   constants/version.ts  — compiled into the bundle (what THIS build is)
//   public/version.json   — served next to the app (what the LATEST deploy is)
// The in-app UpdateBanner compares the two and prompts users to refresh.
// Runs automatically as part of `npm run build:web`.

import { execSync } from 'node:child_process';
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const pkg = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8'));

let sha = 'nogit';
try { sha = execSync('git rev-parse --short HEAD', { cwd: root }).toString().trim(); } catch {}

// Timestamp first: buildId comparisons only need "different means newer exists".
const buildId = `${Date.now()}-${sha}`;

writeFileSync(join(root, 'constants/version.ts'),
`// Generated by scripts/gen-version.mjs on every build — do not edit by hand.
export const APP_VERSION = '${pkg.version}';
export const BUILD_ID = '${buildId}';
`);

mkdirSync(join(root, 'public'), { recursive: true });
writeFileSync(join(root, 'public/version.json'),
  JSON.stringify({ version: pkg.version, buildId }) + '\n');

console.log(`version ${pkg.version} build ${buildId}`);
